apiVersion: v2
name: cert-manager
description: A Helm chart for deploying cert-manager on Kubernetes
type: application
version: 0.1.0

dependencies:
  - name: cert-manager
    version: v1.19.1
    repository: https://charts.jetstack.io