apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sre
  namespace: argocd
spec:
  description: SRE project for managing applications
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
      name: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'