apiVersion: v2
name: ingress-nginx
description: Ingress controller for Kubernetes using NGINX as a reverse proxy and load balancer

type: application
version: 4.12.3
appVersion: 1.25.5

dependencies:
  - name: ingress-nginx
    version: 4.12.3
    repository: https://kubernetes.github.io/ingress-nginx
