apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-tls
  namespace: harbor
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  secretName: harbor-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: harbor.khangvu.dev
  dnsNames:
    - harbor.khangvu.dev
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  secretName: argocd-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: argocd.khangvu.dev
  dnsNames:
    - argocd.khangvu.dev
