{{- if .Values.appProjects.enabled }}
{{- range .Values.appProjects.projects }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationProject
metadata:
  name: {{ .name }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    meta.helm.sh/release-name: {{ $.Release.Name }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: Helm
spec:
  sourceRepos:
{{- range .sourceRepos }}
    - {{ . | quote }}
{{- end }}
  destinations:
{{- range .destinations }}
    - namespace: {{ .namespace | quote }}
      server: {{ .server | quote }}
{{- end }}
  clusterResourceWhitelist:
{{- range .clusterResourceWhitelist }}
    - group: {{ .group | quote }}
      kind: {{ .kind | quote }}
{{- end }}
  namespaceResourceWhitelist:
{{- range .namespaceResourceWhitelist }}
    - group: {{ .group | quote }}
      kind: {{ .kind | quote }}
{{- end }}
---
{{- end }}
{{- end }}