apiVersion: v2
name: metrics-server
description: Metrics Server Helm Chart
type: application
version: 3.13.0
appVersion: 0.8.0

dependencies:
  - name: metrics-server
    version: 3.13.0
    repository: https://kubernetes-sigs.github.io/metrics-server